restaurant/restaurant/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^', include('tablebook.urls'), name='mainpage'),
]

restaurant/tablebook/urls.py
from django.conf.urls import url
from . import views


app_name = 'tablebook'

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^Create-table/$', views.BookView.as_view(), name='Create-table'),

]

restaurant/tablebook/models.py
from django.db import models

# Create your models here.

restaurant/tablebook/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse


class HomeView(generic.TemplateView):
    template_name = 'tablebook/home1.html'


class BookView(generic.TemplateView):
    template_name = 'tablebook/booking.html'

restaurant/tablebook/templates/tablebook/booking.html
{% extends 'tablebook/tablebook.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}Restaurant - Book Table{% endblock %}

{% block link %}
    <script language="javascript" type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.1/p5.js"></script>
    <script language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.1/addons/p5.dom.js"></script>
    <script language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.1/addons/p5.sound.js"></script>

    <script src="{% static 'js/vanilla.js' %}"></script>
    <script src="{% static 'js/booking.js' %}"></script>
    <script src="{% static 'css/bookin1.css' %}"></script>

{% endblock %}

{% block body %}


    <!-- Jumbotron -->
    <div class="container-fluid">
        <div class="row jumbotron">
            <div class="col-xs-12 col-sm-12 col-md-9  col-lg-9 col-xl-10 ">
                <p>Do you have to create table for you? Just click on <b>Create Table!</b></p>
                <p>Do you want to book a table? Just click on cards given below.</p>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3  col-xl-2 ">
                <button type="button" class="btn btn-outline-secondary-btn-lg" >Create Table...</button>
            </div>
        </div>
    </div>

    <div class="container padding">
        <div class="row text-center padding">
            <div class="card-deck">
                <div class="col-xs-12 col-sm-6 col-md-3" id="show1"  onclick="countDown8(3600, 'show1')">
                    <div class="card box shadow">
                        <img src="/static/tablebook/images/table1.png" alt="" class="card-img-top img-fluid cards-size">
                        <div class="card-img-overlay">
                            <h2 class=" card-title display-4">1</h2>
                        </div>
                        <hr>
                        <div class="card-block">
                            <p ><button type="button" class="btn btn-primary" >Book</button></p>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-3" id="show2"  onclick="countDown8(3600, 'show2')">
                    <div class="card box shadow">
                        <img src="/static/tablebook/images/table1.png" alt="" class="card-img-top img-fluid cards-size">
                        <div class="card-img-overlay">
                            <h2 class=" card-title display-4">2</h2>
                        </div>
                        <hr>
                        <div class="card-block">
                            <p ><button type="button" class="btn btn-primary" >Book</button></p>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-3" id="show3"  onclick="countDown8(3600, 'show3')">
                    <div class="card box shadow">
                        <img src="/static/tablebook/images/table1.png" alt="" class="card-img-top img-fluid cards-size">
                        <div class="card-img-overlay">
                            <h2 class=" card-title display-4">3</h2>
                        </div>
                        <hr>
                        <div class="card-block">
                            <p ><button type="button" class="btn btn-primary" >Book</button></p>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-3" id="show4"  onclick="countDown8(3600, 'show4')">
                    <div class="card box shadow">
                        <img src="/static/tablebook/images/table1.png" alt="" class="card-img-top img-fluid cards-size">
                        <div class="card-img-overlay">
                            <h2 class=" card-title display-4">4</h2>
                        </div>
                        <hr>
                        <div class="card-block">
                            <p ><button type="button" class="btn btn-primary" >Book</button></p>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-3" id="show5"  onclick="countDown8(3600, 'show5')">
                    <div class="card box shadow">
                        <img src="/static/tablebook/images/table1.png" alt="" class="card-img-top img-fluid cards-size">
                        <div class="card-img-overlay">
                            <h2 class=" card-title display-4">5</h2>
                        </div>
                        <hr>
                        <div class="card-block">
                            <p ><button type="button" class="btn btn-primary" >Book</button></p>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-3" id="show6"  onclick="countDown8(3600, 'show6')">
                    <div class="card box shadow">
                        <img src="/static/tablebook/images/table1.png" alt="" class="card-img-top img-fluid cards-size">
                        <div class="card-img-overlay">
                            <h2 class=" card-title display-4">6</h2>
                        </div>
                        <hr>
                        <div class="card-block">
                            <p ><button type="button" class="btn btn-primary" >Book</button></p>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-3" id="show7"  onclick="countDown8(3600, 'show7')">
                    <div class="card box shadow">
                        <img src="/static/tablebook/images/table1.png" alt="" class="card-img-top img-fluid cards-size">
                        <div class="card-img-overlay">
                            <h2 class=" card-title display-4">7</h2>
                        </div>
                        <hr>
                        <div class="card-block">
                            <p ><button type="button" class="btn btn-primary" >Book</button></p>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-3 show1" id="show8"  onclick="countDown8(3600, 'show8')">
                    <div class="card box shadow">
                        <img src="/static/tablebook/images/table1.png" alt="" class="card-img-top img-fluid cards-size">
                        <div class="card-img-overlay">
                            <h2 class=" card-title display-4">8</h2>
                        </div>
                        <hr>
                        <div class="card-block " id="button">
                            <p class="card-title"  ><button  class="btn btn-primary" >Book</button></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

restaurant/tablebook/templates/tablebook/home1.html
{% extends 'tablebook/tablebook.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}Restaurant{% endblock %}


{% block body %}


    <!-- Jumbotron -->
    <div class="container-fluid">
        <div class="row jumbotron">
            <div class="col-xs-12 col-sm-12 col-md-9  col-lg-9 col-xl-10 ">
                Do you want to book table for you? Just click on <b>Book Table!<b>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3  col-xl-2 ">
                <a href="{% url 'tablebook:Create-table' %}" >
                    <button type="button" class="btn btn-outline-secondary-btn-lg" >Book Table...</button>
                </a>
            </div>
        </div>
    </div>

    <!-- Welcome Section -->
    <div class="container-fluid padding" >
        <div class="row welcome text-center">
            <div class="col-12">
                <h1 class="display-4 welcome-font">Welcome!</h1>
            </div>
            <hr>
            <div class="col-12">
                <p class="lead">
                    Welcome, In our restaurent. We provide all services, please enjoy!...
                </p>
            </div>
        </div>
    </div>

{% endblock %}

restaurant/tablebook/templates/tablebook/tablebook.html
{% load staticfiles %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Restaurant</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Monoton" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Caveat+Brush" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Merienda" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <script src="{% static 'js/home.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block link %}{% endblock %}

</head>
<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top ">
        <div class="container-fluid">
            <a href="{% url 'tablebook:home' %}" class="navbar-brand logo"> Restaurant </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a href="{% url 'tablebook:home' %}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link">Join Our Team</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link">Contact Us</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link">About Us</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

     <!-- Dynamic Content Area -->
    {% block body %}
    {% endblock %}

</body>
</html>